plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/journal/:title"
  