title: damondriscoll
description: a site where damon driscoll writes things
url: https://blog.damondriscoll.com
author: damon driscoll

defaults:
  -
    scope:
      path: "_pages/"
      type: "pages"
    values:
      permalink: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/post/:title"

include:
 - _images
 - _pages
  
