title: damondriscoll
description: a site where damon driscoll writes things
url: https://damondriscoll.com
author: damon driscoll

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:title"

feed:
  path: /rss/
  